#pragma once
#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <ctime>

using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::string;
using std::copy;
using std::swap;
using std::isdigit;
using std::min;
using std::numeric_limits;
using std::streamsize;